FROM node:22-alpine

WORKDIR /app

# Копируем package-файлы и устанавливаем зависимости
COPY password-analyzer-backend/package.json password-analyzer-backend/package-lock.json ./
RUN npm ci

# Копируем исходники
COPY password-analyzer-backend/ ./

# NestJS dev-сервер
EXPOSE 3001
CMD ["npm", "run", "start:dev"]
